# -*- coding: utf-8 -*-
"""AI_interview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-HvdsZQUHOcZKUgpDMAVfqKSHBgbgki

### Facial Emotion Recognition Data Requirements

For facial emotion recognition, the primary data type required is **annotated image and/or video datasets**. These datasets need to include a diverse range of human faces exhibiting various emotions.

*   **Image Datasets**: Each image should be labeled with a specific emotion category.
    *   **Desired Resolution**: Images should preferably have a minimum resolution of `640x480` pixels to capture sufficient facial detail. Higher resolutions are better, but a balance with dataset size and processing power is necessary.
    *   **Emotion Categories**: Standard emotion categories typically include `happy`, `sad`, `angry`, `fearful`, `disgusted`, `surprised`, and `neutral`. Additional categories like `contempt` or `excitement` may be considered for more nuanced analysis.

*   **Video Datasets**: Videos are crucial for capturing temporal dynamics of emotion expression. Each frame or segment of the video should be labeled with emotion categories.
    *   **Desired Frame Rate**: A minimum of `24-30 frames per second (fps)` is recommended to capture subtle emotional shifts.
    *   **Duration**: Video clips should vary in duration, typically from `3-10 seconds`, to show the onset, apex, and offset of emotional expressions.
    *   **Annotation**: Frame-level or event-based annotation for emotions, potentially including intensity levels.

### Open-Source Datasets for Data Acquisition

To acquire data for both facial emotion recognition and spoken answer evaluation, we can leverage existing open-source datasets. This approach saves time and resources compared to creating custom datasets from scratch.

#### Facial Emotion Recognition Datasets:

*   **FER2013**: A widely used dataset consisting of `48x48` pixel grayscale images of faces, labeled with 7 emotion categories (0=Angry, 1=Disgust, 2=Fear, 3=Happy, 4=Sad, 5=Surprise, 6=Neutral). It contains ~35,000 images.
*   **AffectNet**: A large dataset with over 1 million facial images from the internet, manually annotated for the presence of 11 discrete emotion categories and the intensity of valence and arousal. It's more diverse and larger than FER2013.
*   **CK+ (Extended Cohn-Kanade Dataset)**: A dataset of posed and spontaneous facial expressions. It includes sequences of images from neutral to peak expression, along with FACS (Facial Action Coding System) action unit codes and emotion labels for peak frames. It contains ~600 sequences from 123 subjects.
*   **RAF-DB (Real-world Affective Faces Database)**: A diverse dataset containing approximately 30,000 facial images with accurate annotations of 7 basic and 11 compound emotion categories. The images are collected from real-world conditions.
*   **JAFFE (Japanese Female Facial Expression) Database**: Contains 213 images of 7 facial expressions (6 basic facial expressions + 1 neutral) posed by 10 Japanese female models. Each image is rated on 6 emotion adjectives by 60 Japanese subjects.

#### Spoken Answer Evaluation Datasets:

*   **VCTK (Voice Cloning Toolkit) Corpus**: Contains speech data uttered by 109 native speakers of English with various accents. Each speaker reads around 400 sentences. While primarily for speech synthesis, it can be used for training robust ASR models which are crucial for transcription accuracy in spoken answer evaluation.
*   **LibriSpeech**: A corpus of approximately 1000 hours of 16kHz read English speech, prepared by Google for automatic speech recognition (ASR) research. It's suitable for training and evaluating ASR systems that would transcribe spoken answers.
*   **Common Voice (Mozilla)**: A large, open-source, multi-language dataset of voices. Volunteers record sentences from a public domain text, and other volunteers validate the recordings. This can be used to build custom ASR models or enhance existing ones for specific accents or linguistic nuances.
*   **AMI Meeting Corpus**: Contains recordings of naturally occurring meetings. This dataset includes audio, video, and rich annotations (transcripts, speaker turns, named entities, etc.), which could be valuable for understanding conversational dynamics in spoken answers, though it's not directly for 'answer evaluation'.
*   **Custom Datasets for Question-Answering**: While no large public dataset directly provides 'spoken answers evaluated against questions', components can be found:
    *   **SQuAD (Stanford Question Answering Dataset)**: A reading comprehension dataset, consisting of questions posed by crowdworkers on a set of Wikipedia articles, where the answer to every question is a segment of text, or span, from the corresponding reading passage. This is text-based but provides a structure for question-answer pairs.
    *   **NarrativeQA**: Requires models to answer questions by reading passages and/or summaries of books and movies. Again, text-based, but valuable for question-answering logic.

For spoken answer evaluation, it's highly probable that a custom dataset will need to be created, combining audio recordings of responses to specific interview questions with expert-rated quality scores and accurate transcripts, as fully pre-packaged datasets for this exact purpose are less common.
"""

!pip install speechrecognition
!pip install sentence-transformers
!pip install sounddevice
!pip install transformers
!pip install torch

!pip install speechrecognition
import speech_recognition as sr
import torch
import numpy as np
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

questions = [
    {
        "question": "Explain what is Machine Learning?",
        "ideal_answer": "Machine learning is a subset of artificial intelligence that enables systems to learn from data and improve without being explicitly programmed."
    },
    {
        "question": "What is overfitting?",
        "ideal_answer": "Overfitting occurs when a model learns noise in the training data and performs poorly on unseen data."
    },
    {
        "question": "Explain CNN.",
        "ideal_answer": "A Convolutional Neural Network is a deep learning model mainly used for image processing and computer vision tasks."
    }
]

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

df = pd.read_csv(
    '/content/drive/MyDrive/fer2013.csv',
    encoding='latin1',
    engine='python',
    compression='zip',
    on_bad_lines='warn' # This should skip malformed lines for the python engine
)

df=pd.DataFrame(df)
df.head()

emotions = { #list of available emotions in the dataset
    0:"Angry",
    1:"Disgust",
    2:"Fear",
    3:"Happy",
    4:"Sad",
    5:"Surprize",
    6:"Neutral"
}

import matplotlib.pyplot as plt

def visualize_images(n_img=4):
    indices = np.random.randint(0,df.shape[0],size=n_img)
#     print(indices)
    plt.figure(figsize=(20,20))
    for i,l in zip(indices,range(0,len(indices))):
        image_ar = np.array([i for i in  df['pixels'][i].split()] , dtype='float')
        pixels = np.reshape(image_ar,(48,48))
        ax = plt.subplot(4,4,l+1)
        plt.imshow(pixels,cmap='gray')
        plt.title(emotions[df['emotion'][i]]+" ["+str(i)+"]")
        plt.xticks()
        plt.yticks([])
        plt.axis("off")
visualize_images(12)

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense,Input,Dropout,GlobalAveragePooling2D,Flatten,Conv2D,BatchNormalization,Activation,MaxPooling2D
from tensorflow.keras.models import Model,Sequential
from tensorflow.keras.optimizers import Adam,SGD,RMSprop

X_train,y_train = [],[]
X_val,y_val = [],[]
X_test,y_test = [],[]
for index,row in df.iterrows():
    k = row['pixels'].split(" ")
    if row['Usage'] == 'Training':
        X_train.append(np.array(k))
        y_train.append(row['emotion'])
    elif row['Usage'] == 'PrivateTest':
        X_test.append(np.array(k))
        y_test.append(row['emotion'])
    elif row['Usage'] == 'PublicTest':
        X_val.append(np.array(k))
        y_val.append(row['emotion'])

X_train = np.array(X_train,dtype='float')
y_train = np.array(y_train)
X_test = np.array(X_test,dtype='float')
y_test = np.array(y_test)
X_val = np.array(X_val,dtype='float')
y_val = np.array(y_val)

X_train.shape,y_train.shape,X_test.shape,y_test.shape,X_val.shape,y_val.shape

from tensorflow.keras.utils import to_categorical

X_train = X_train.reshape(X_train.shape[0],48,48,1)
X_test = X_test.reshape(X_test.shape[0],48,48,1)
X_val = X_val.reshape(X_val.shape[0],48,48,1)

y_train = to_categorical(y_train,num_classes=7)
y_test = to_categorical(y_test,num_classes=7)
y_val = to_categorical(y_val,num_classes=7)

X_train.shape,y_train.shape,X_test.shape,y_test.shape,X_val.shape,y_val.shape

"""PREPROCESSING IMAGES"""

no_of_classes=7

model=Sequential()

#1st CNN layer
model.add(Conv2D(64,(3,3),padding="same",input_shape=(48,48,1)))
model.add(BatchNormalization())
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))


#2nd CNN layer
model.add(Conv2D(128,(5,5),padding="same"))
model.add(BatchNormalization())
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

#3rd CNN layer
model.add(Conv2D(512,(3,3),padding="same"))
model.add(BatchNormalization())
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

#4th CNN layer
model.add(Conv2D(512,(3,3), padding='same'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())

#Fully connected 1st layer
model.add(Dense(256))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.25))
# Fully connected layer 2nd layer
model.add(Dense(512))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.25))

model.add(Dense(no_of_classes,activation="softmax"))
model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

checkpointer = [EarlyStopping(monitor = 'val_accuracy', verbose = 1,
                              restore_best_weights=True,mode="max",patience = 10),
                              ModelCheckpoint('best_model.h5',monitor="val_accuracy",verbose=1,
                              save_best_only=True,mode="max")]

history = model.fit(
    X_train,
    y_train,
    batch_size=32,
    epochs=30,
    callbacks=checkpointer,
    validation_data=(X_val,y_val)
)

"""FITTING THE MODEL WITH THE TRAINING AND VALIDATION DATA"""

def loss_plot(history):
  plt.plot(history.history["loss"],'r', label="Training Loss")
  plt.plot(history.history["val_loss"],'b', label="Validation Loss")
  plt.legend()

loss_plot(history)

preds = model.predict(X_test)
y_pred = np.argmax(preds , axis = 1 )

def check_images(X_test,y_pred,label_dict={}):

  figure = plt.figure(figsize=(20, 8))
  for i, index in enumerate(np.random.choice(X_test.shape[0], size=24, replace=False)):
      ax = figure.add_subplot(4, 6, i + 1, xticks=[], yticks=[])
      ax.imshow(np.squeeze(X_test[index]),cmap="gray")
      predict_index = label_dict[(y_pred[index])]
      true_index = label_dict[np.argmax(y_test,axis=1)[index]]

      ax.set_title("{} ({})".format((predict_index),
                                    (true_index)),
                                    color=("green" if predict_index == true_index else "red"))
check_images(X_test,y_pred,emotions)

from tensorflow.keras.metrics import  CategoricalAccuracy

X_test.shape

y_hat=model.predict(X_test)
acc = CategoricalAccuracy()
acc.update_state(y_test,y_hat)
acc.result().numpy()

model.evaluate(X_test,y_test)



plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(X_test[i])
    plt.xlabel(emotions[y_pred[i]])
plt.show()

plt.style.use('dark_background')

plt.figure(figsize=(20,10))
plt.subplot(1, 2, 1)
plt.suptitle('Optimizer : Adam', fontsize=10)
plt.ylabel('Loss', fontsize=16)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend(loc='upper right')

plt.subplot(1, 2, 2)
plt.ylabel('Accuracy', fontsize=16)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend(loc='lower right')
plt.show()



"""### Saving Your Trained Model

After training, you can save your Keras model, including its architecture, weights, and optimizer state, to a file. This allows you to load it later without needing to retrain it.

Since you are already using `ModelCheckpoint` to save the best model during training, you have `best_model.h5` saved. If you want to save the final model after all epochs (which might not be the 'best' if early stopping triggered), you can use `model.save()`.
"""

import tensorflow as tf

# The ModelCheckpoint callback already saved the best model to 'best_model.h5'
# You can load it directly. If you wanted to save the final model after training:
# model.save('final_emotion_model.h5')

print("Model saved by ModelCheckpoint during training as 'best_model.h5'.")

"""### Loading Your Saved Model

To access and use your trained model in a new session or script, you just need to load it from the saved file. You do not need to redefine the model architecture or retrain it.
"""

import tensorflow as tf

# Load the best model saved during training
loaded_model = tf.keras.models.load_model('best_model.h5')

# Now you can use 'loaded_model' for predictions or further evaluation
print("Model loaded successfully!")
loaded_model.summary()

# Example: Evaluate the loaded model on the test data
loss, accuracy = loaded_model.evaluate(X_test, y_test, verbose=0)
print(f"Loaded model test accuracy: {accuracy:.4f}")

"""By following these steps, you only need to run the model definition and training code once. For subsequent uses, you can simply load the saved model and use it for inference."""

